server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: root
    password: cy12367890
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://180.76.99.222:3306/aho?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    type: com.zaxxer.hikari.HikariDataSource


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


